# Data Visualisations:

Dataset from Kaggle : **"MyAnimeList"** by *Azathoth*  
Source: https://www.kaggle.com/datasets/azathoth42/myanimelist/data (requires login)

---

### Essential Libraries

Let us begin by importing the essential Python Libraries.

> NumPy : Library for Numeric Computations in Python  
> Pandas : Library for Data Acquisition and Preparation  
> Matplotlib : Low-level library for Data Visualization  
> Seaborn : Higher-level library for Data Visualization

In [12]:
# Basic Libraries
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt # we only need pyplot
sb.set() # set the default Seaborn style for graphics

## Import cleaned Data
---

In [13]:
animelist = pd.read_csv('DataSets/Cleaned data/tv_only_success_metric.csv')
animelist.head()

,title,type,source,episodes,status,airing,rating,score,scored_by,rank,...,Related_Alternative version,Related_Prequel,Related_Summary,Related_Other,Related_Spin-off,Related_Alternative setting,Related_Character,Related_Parent story,Related_Full story,success
0,Inu x Boku SS,TV,Manga,12,Finished Airing,False,PG-13 - Teens 13 or older,7.63,139250,1274.0,...,0,0,0,0,0,0,0,0,0,1
1,Seto no Hanayome,TV,Manga,26,Finished Airing,False,PG-13 - Teens 13 or older,7.89,91206,727.0,...,1,0,0,0,0,0,0,0,0,1
2,Shugo Chara!! Doki,TV,Manga,51,Finished Airing,False,PG - Children,7.55,37129,1508.0,...,0,1,0,0,0,0,0,0,0,1
3,Princess Tutu,TV,Original,38,Finished Airing,False,PG-13 - Teens 13 or older,8.21,36501,307.0,...,0,0,1,0,0,0,0,0,0,1
4,Bakuman. 3rd Season,TV,Manga,25,Finished Airing,False,PG-13 - Teens 13 or older,8.67,107767,50.0,...,0,2,0,1,0,0,0,0,0,1

In [14]:
animelist.describe()

,episodes,score,scored_by,rank,popularity,members,favorites,year,days_aired,duration_minutes,...,Related_Alternative version,Related_Prequel,Related_Summary,Related_Other,Related_Spin-off,Related_Alternative setting,Related_Character,Related_Parent story,Related_Full story,success
count,3310.000000,3310.000000,3.310000e+03,3310.000000,3310.000000,3.310000e+03,3310.000000,3310.000000,3310.000000,3310.000000,...,3310.000000,3310.000000,3310.000000,3310.000000,3310.000000,3310.000000,3310.000000,3310.000000,3310.000000,3310.000000
mean,31.930816,7.015677,3.660787e+04,3858.580060,3830.762538,7.307188e+04,1186.556193,1970.251964,233.175529,21.313771,...,0.169184,0.255287,0.103625,0.200604,0.097885,0.144109,0.033233,0.014502,0.002115,3.503927
std,62.878949,0.781273,8.005618e+04,2800.324643,3326.865571,1.369290e+05,5144.068699,261.098466,418.718767,6.693307,...,0.583664,0.489010,0.366081,0.666697,0.518117,1.036397,0.221498,0.131596,0.067295,1.451487
min,2.000000,3.310000,2.000000e+00,1.000000,1.000000,3.500000e+01,1.000000,0.000000,-49.000000,0.250000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,12.000000,6.550000,8.375000e+02,1581.750000,1035.500000,2.691250e+03,7.000000,2000.000000,78.000000,23.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
50%,22.000000,7.040000,6.720500e+03,3435.000000,2794.500000,1.819000e+04,56.000000,2007.000000,162.000000,24.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000
75%,35.000000,7.520000,3.459150e+04,5540.750000,6219.500000,8.052175e+04,426.250000,2014.000000,267.000000,24.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000
max,1787.000000,9.250000,1.009477e+06,12867.000000,14187.000000,1.456378e+06,106895.000000,2018.000000,9540.000000,50.000000,...,7.000000,6.000000,6.000000,12.000000,10.000000,14.000000,5.000000,2.000000,3.000000,5.000000

In [15]:
numeric_data = pd.DataFrame(animelist[['episodes', 'score', 'scored_by', 'rank', 'popularity', 'members', 'favorites', 'duration_minutes']])
numeric_data.describe().round(2)

,episodes,score,scored_by,rank,popularity,members,favorites,duration_minutes
count,3310.00,3310.00,3310.00,3310.00,3310.00,3310.00,3310.00,3310.00
mean,31.93,7.02,36607.87,3858.58,3830.76,73071.88,1186.56,21.31
std,62.88,0.78,80056.18,2800.32,3326.87,136929.05,5144.07,6.69
min,2.00,3.31,2.00,1.00,1.00,35.00,1.00,0.25
25%,12.00,6.55,837.50,1581.75,1035.50,2691.25,7.00,23.00
50%,22.00,7.04,6720.50,3435.00,2794.50,18190.00,56.00,24.00
75%,35.00,7.52,34591.50,5540.75,6219.50,80521.75,426.25,24.00
max,1787.00,9.25,1009477.00,12867.00,14187.00,1456378.00,106895.00,50.00

## Distributions of all numeric variables
---

In [ ]:
# Draw the distributions of all variables
f, axes = plt.subplots(8, 3, figsize=(18, 25))

count = 0
for var in numeric_data:
    sb.boxplot(data = numeric_data[var], orient = "h", ax = axes[count,0])
    sb.histplot(data = numeric_data[var], ax = axes[count,1])
    sb.violinplot(data = numeric_data[var], orient = "h", ax = axes[count,2])
    count += 1

## Correlation of all variables
---

In [ ]:
# Correlation Matrix
print(numeric_data.corr())

# Heatmap of the Correlation Matrix
f = plt.figure(figsize=(10, 10))
sb.heatmap(numeric_data.corr(), vmin = -1, vmax = 1, linewidths = 1,
           annot = True, fmt = ".2f", annot_kws = {"size": 18}, cmap = "RdBu")

### Pair Plots 
---

In [ ]:
# Draw pairs of variables against one another
sb.pairplot(data = numeric_data)

In [ ]:
## score vs number of scores
f = plt.figure(figsize=(16, 8))
plt.scatter(numeric_data['score'], numeric_data['members'])

# Set labels and title
plt.xlabel('Overall Score')
plt.ylabel('Number of Scores')
plt.title('Anime Score vs. Number of Scores')
plt.show()

In [ ]:
# Assuming animelist is your DataFrame containing genre columns

# Sum the occurrences of each genre across all rows
genre_list = [col for col in sorted_df.columns if 'Genre_' in col]

genre_counts = animelist[genre_list].sum()

genre_counts_df = genre_counts.reset_index()
genre_counts_df.columns = ['Genre', 'Count']

# Sort the DataFrame by count
genre_counts_df = genre_counts_df.sort_values(by='Count', ascending=False)

print(genre_counts_df)
print()

# Create the bar plot
sb.catplot(x='Count', y='Genre', kind='bar', data=genre_counts_df, height=10, aspect=2)
plt.xlabel('Count')
plt.ylabel('Genre')
plt.title('Count of Each Genre')
plt.show()

## Categorist types of animes
---

In [ ]:
# What are the Type of anime
animelist_type = animelist['type'].unique()
animelist_type

In [ ]:
# What are the value per type
type_count = animelist['type'].value_counts()
print(type_count)

sb.catplot(y = "type", data = animelist, kind = "count")

## Top 50 animes list (popularity)
---
    
    Base on popularity and compare whether member.

In [ ]:
# Assuming animelist is your DataFrame containing the necessary columns including 'popularity' and 'title' and genre columns
df = pd.DataFrame(animelist)
df = df[df['popularity'] != 0]

# Sort DataFrame by popularity
sorted_df = df.sort_values(by='popularity', ascending=True)

# Get the top 10 titles by popularity
top_50 = sorted_df.head(50)

print("Top 50 titles by popularity:")
print(top_50[['title', 'popularity']])

In [ ]:
# Iterate over rows using apply()
print("Top 50 titles by popularity with genre:")
print()
top_50.apply(lambda row: print(f"{row['popularity']}: {row['title']} - Genre: {', '.join([col for col in sorted_df.columns if row[col] == 1 and 'Genre_' in col])}"), axis = 1)

### Comparing to the top 10 anime what are the genre is popular
---

In [ ]:
top_50_genre_counts = top_50[['Action', 'Adventure', 'Cars', 'Comedy', 'Dementia', 'Demons', 'Drama', 'Ecchi', 'Fantasy', 'Game', 'Harem', 'Hentai', 'Historical', 'Horror', 'Josei', 'Kids', 'Magic', 'Martial Arts', 'Mecha', 'Military', 'Music', 'Mystery', 'NA', 'Parody', 'Police', 'Psychological', 'Romance', 'Samurai', 'School', 'Sci-Fi', 'Seinen', 'Shoujo', 'Shoujo Ai', 'Shounen', 'Shounen Ai', 'Slice of Life', 'Space', 'Sports', 'Super Power', 'Supernatural', 'Thriller', 'Vampire', 'Yaoi', 'Yuri']].sum()

top_50_genre_counts = top_50_genre_counts.reset_index()
top_50_genre_counts.columns = ['Genre', 'Count']

# Sort the DataFrame by count
top_50_genre_counts = top_50_genre_counts.sort_values(by='Count', ascending=False)
top_50_genre_counts = top_50_genre_counts[top_50_genre_counts['Count'] > 0]

print("Genres in the top 10 most popular anime:")
print(top_50_genre_counts)
print()

# Create the bar plot
sb.catplot(x='Count', y='Genre', kind='bar', data=top_50_genre_counts, height=10, aspect=2)
plt.xlabel('Count')
plt.ylabel('Genre')
plt.title('Count of Each Genre')
plt.show()

## Top 50 anime list (members)
---

    Base on comparison both popularity and members, we see that popularity is base on member.

In [ ]:
## most watched show 
df = pd.DataFrame(animelist)

# Sort DataFrame by popularity
sorted_df = df.sort_values(by='members', ascending=False)

# Get the title with the highest popularity
top_50 = sorted_df.head(50)[['title', 'members']]

print("Top 50 titles by most watched:")
print(top_50[['title', 'members']])

From above top 10 shows, we can conclude that number of watchers determine the popularity.